name: PiricraftCore
description: $description
version: '${version}'

main: fr.piricraft.piricraftCore.PiricraftCore
api-version: '26.2'
load: POSTWORLD
libraries:
  - org.xerial:sqlite-jdbc:3.50.3.0

authors: [ Lepipassier ]
website: https://github.com/Piricraft

commands:
  money:
    description: View your own balance, or player's balance.
    aliases:
      - bal
      - balance
    usage: /money [joueur]
  pay:
    description: Transfer money to player.
    usage: /pay [joueur] [montant]
