// This class was generated by IA.

package fr.piricraft.piricraftCore.managers;

import fr.piricraft.piricraftCore.PiricraftCore;
import fr.piricraft.piricraftCore.models.PlayerProfile;

import java.io.File;
import java.sql.*;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;

public class DatabaseManager {

    private final PiricraftCore plugin;
    private Connection connection;
    private final Map<UUID, PlayerProfile> profileCache = new ConcurrentHashMap<>();

    public DatabaseManager(PiricraftCore plugin) {
        this.plugin = plugin;
    }

    public void initDatabase() {
        try {
            if (!plugin.getDataFolder().exists()) {
                plugin.getDataFolder().mkdirs();
            }

            File dbFile = new File(plugin.getDataFolder(), "database.db");
            String url = "jdbc:sqlite:" + dbFile.getAbsolutePath();

            connection = DriverManager.getConnection(url);

            String createTableSQL = """
                CREATE TABLE IF NOT EXISTS piricraft_players (
                    uuid VARCHAR(36) PRIMARY KEY,
                    name VARCHAR(16) NOT NULL,
                    balance DOUBLE NOT NULL,
                    first_join BIGINT NOT NULL
                );
            """;

            try (Statement statement = connection.createStatement()) {
                statement.execute(createTableSQL);
            }

            plugin.getLogger().info("Base de données SQLite initialisée avec succès !");

        } catch (SQLException e) {
            plugin.getLogger().severe("Impossible de se connecter à la base de données !");
            e.printStackTrace();
        }
    }

    // Load profile
    public CompletableFuture<PlayerProfile> loadProfileAsync(UUID uuid, String name) {
        return CompletableFuture.supplyAsync(() -> {
            String query = "SELECT * FROM piricraft_players WHERE uuid = ?;";

            try (PreparedStatement statement = connection.prepareStatement(query)) {
                statement.setString(1, uuid.toString());
                ResultSet result = statement.executeQuery();

                if (result.next()) {
                    double balance = result.getDouble("balance");
                    long firstJoin = result.getLong("first_join");

                    PlayerProfile profile = new PlayerProfile(uuid, name, balance, firstJoin);
                    profileCache.put(uuid, profile);
                    return profile;
                } else {
                    PlayerProfile newProfile = new PlayerProfile(uuid, name, 100.0);

                    insertNewProfile(newProfile);
                    profileCache.put(uuid, newProfile);
                    return newProfile;
                }

            } catch (SQLException e) {
                e.printStackTrace();
                return null;
            }
        });
    }


    private void insertNewProfile(PlayerProfile profile) {
        String insertSQL = "INSERT INTO piricraft_players (uuid, name, balance, first_join) VALUES (?, ?, ?, ?);";

        try (PreparedStatement statement = connection.prepareStatement(insertSQL)) {
            statement.setString(1, profile.getPlayerUuid().toString());
            statement.setString(2, profile.getPlayerName());
            statement.setDouble(3, profile.getBalance());
            statement.setLong(4, profile.getFirstJoinTimestamp());
            statement.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public CompletableFuture<Void> saveProfileAsync(PlayerProfile profile) {
        return CompletableFuture.runAsync(() -> {
            if (profile == null) return;

            String updateSQL = "UPDATE piricraft_players SET name = ?, balance = ? WHERE uuid = ?;";

            try (PreparedStatement statement = connection.prepareStatement(updateSQL)) {
                statement.setString(1, profile.getPlayerName());
                statement.setDouble(2, profile.getBalance());
                statement.setString(3, profile.getPlayerUuid().toString());
                statement.executeUpdate();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        });
    }

    public void saveAllProfilesAsync() {
        for (PlayerProfile profile : profileCache.values()) {
            saveProfileAsync(profile);
        }
    }

    public void unloadProfile(UUID uuid) {
        PlayerProfile profile = profileCache.get(uuid);
        if (profile != null) {
            saveProfileAsync(profile).thenRun(() -> profileCache.remove(uuid));
        }
    }

    public PlayerProfile getProfileFromCache(UUID uuid) {
        return profileCache.get(uuid);
    }

    public void closeConnection() {
        try {
            if (connection != null && !connection.isClosed()) {
                connection.close();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}